blank_issues_enabled: false
contact_links:
  - name: Feature Request
    url: https://swiftdatatables.pavankataria.com/vote
    about: Vote for features or submit new ideas â€” your votes shape the roadmap
